### ISSUE TITLE
Clarification of update instructions please

### ISSUE THREAD

**Issue by Grandpa-G** [roman380/tmhare.mvps.org-vcam#1]
For step #2 in the Update section:
`Then, edit directshow.props and modify line with WindowsClassicSamplesDir to have it point to root of repository from step 1 above`
could you clarify exactly where I should be pointing to? Is it the repository on GitHub, or a folder on my computer that starts of the root of the entire repository or what?

Thanks.

**Comment by roman380** [comment]
You need to do the following:

1. Clone [this repository](https://github.com/roman380/Windows-classic-samples/tree/directshow/Samples/Win7Samples/multimedia/directshow) somewhere, note that you need "directshow" branch of it:

```
git clone https://github.com/roman380/Windows-classic-samples.git -b directshow
```

2. Let's say you have repository from step above cloned into `C:\Repo\Windows-classic-samples`

3. Clone this VCam repository and edit `directshow.props` in the root directory changing line 5 https://github.com/roman380/tmhare.mvps.org-vcam/blob/main/directshow.props#L5 and placing directory from step 2 instead of the existing path.

```
<WindowsClassicSamplesDir>C:\Repo\Windows-classic-samples</WindowsClassicSamplesDir>
```

4. Then you build `Samples/Win7Samples/multimedia/directshow/directshow.sln` from the repository from step 1 so that it gets you static libraries. 

5. You are ready to build the VCam now using `vcam.sln` in the root of this repository.

**Comment by roman380** [comment]
This is the example of the change (made by another user): https://github.com/genesys-albert/tmhare.mvps.org-vcam/commit/1008de694ee4a60c43d963dcf27b9372292f90e7

**Comment by Grandpa-G** [comment]
I have a USB video camera that works fine in simple video display. However, if I use it as the source in other programs, there is a small lag, which makes it unusable. I used the GraphEditor and it put in a MJPEG decompressor and that shows the lag as well.

 

I don’t know if this your area of expertise, but do you think I have a chance of making a filter that will somehow remove the lag? I don’t know if I can get the technical specs on the camera.

 

If you don’t know or don’t want to get involved, that is fine, just say so. It won’t hurt my feelings.

 

Thanks.

**Comment by roman380** [comment]
First of all, I don't know what "simple video display" is.

Second, USB cameras that produce JPEG compressed video are known to have an associated lag. Although you don't give any idea what order of lag, in milliseconds, you observe and what makes it unacceptable to you.

Then, this lag problem is probably unlreated to this repository ni any way, meaming VCam is using DirectShow API similarly to USB cams but that's all these share.

And then finally, whatever you do you eve if you do it right you will probably end up with 60-80-100 ms lag end to end from camera's capture to display. If you suffer from longer lag, then it can probably be fixed via software.
